services:
  opencep-api:
    image: ghcr.io/ricardoapaes/opencep:latest
    build:
      context: .
      dockerfile: Dockerfile
      args:
        - OPENCEP_VERSION=${OPENCEP_VERSION:-2.0.1}
      x-bake:
        cache-from:
          - type=local,src=/tmp/.buildx-cache
        cache-to:
          - type=local,dest=/tmp/.buildx-cache
    volumes:
      - ./nginx.conf:/etc/nginx/conf.d/default.conf
      - ./index.html:/usr/share/nginx/html/index.html
    ports:
      - "8080:80"
    restart: always