services:
  cep-search:
    image: opencep-search:test
    build:
      target: search-server-test

  opencep-api:
    image: opencep-nginx:test
    build:
      target: nginx-server-test

networks:
  default:
    internal: true
